apiVersion: v1
kind: Service
metadata:
  name: tripviewer 
  labels:
    run: tripviewer
spec:
  type: ClusterIP # Or cluster ip if svc does not need an external ip
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: tripviewer
